title: TarterBlog
author: Steve Tarter
email: steve@tarterware.com
description: > # this means to ignore newlines until "baseurl:"
  Musings and fumings of Steve Tarter, programmer, dreamer, and fool.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
